spring:
  sql:
    init:
      mode: always
  datasource:
    data: classpath:data.sql
    url: jdbc:h2:file:./mydb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect

h2:
  console:
    enabled: true
    path: /h2-console
    settings:
      trace: false
      web-allow-others: false

server:
  port: 8080

logging:
  level:
    root: INFO
